/camera/camera1:
  ros__parameters:
    ir_width: 640
    ir_height: 480
    ir_fps: 30
    ir_frame_id: "camera1_ir_frame"
    optical_ir_frame_id: "camera1_optical_ir_frame"
    enable_ir: true
    depth_width: 640
    depth_height: 360
    depth_fps: 30
    depth_frame_id: "camera1_depth_frame"
    optical_depth_frame_id: "camera1_optical_depth_frame"
    enable_depth: true
    publish_tf: true
    tf_publish_rate: 10.0
    reconnect_timeout: 6.0
    depth_align: true
    serial_number: "CH2PB10004T"
    camera_link_frame_id: "camera1_link"
    number_of_devices: 2
    uvc_camera:
      enable: true
      width: 640
      height: 360
      fps: 30
      format: "mjpeg"
      vid: 0x2bc5
      pid: 0x0559
      color_frame_id: "camera1_color_frame"
      optical_color_frame_id: "camera1_optical_color_frame"
